version: 2
updates:
  - package-ecosystem: "gomod"
    directory: '/'
    schedule:
      interval: "weekly"
    assignees:
      - walnuts1018
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    assignees:
      - walnuts1018
  - package-ecosystem: docker
    directory: '/'
    schedule:
      interval: "weekly"
    assignees:
      - walnuts1018
