services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.local
    working_dir: /app
    tty: true
    volumes:
      - go_pkg_mod:/go/pkg/mod
      - root_cache_go_build:/root/.cache/go-build
    ports:
      - "8080:8080"
    environment:
      LOG_LEVEL: debug
      LOG_TYPE: "text"
      ADMIN_TOKEN: "mockadmintoken"
      JWT_SIGN_SECRET: "mockjwtsecret"
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: mockaccesskey
      MINIO_SECRET_KEY: mocksecretkey
      MinIOUseSSL: "false"
      FFMPEG_HW_ACCEL: "false"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    depends_on:
      - minio
    develop:
      watch:
        - action: rebuild
          path: ./
  minio:
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio_data:/export
      - minio_config:/root/.minio
    environment:
      MINIO_ACCESS_KEY: mockaccesskey
      MINIO_SECRET_KEY: mocksecretkey
    command: server /export --console-address ":9001"

networks:
  default: {}

volumes:
  minio_data:
    driver: local
  minio_config:
    driver: local
  go_pkg_mod:
    driver: local
  root_cache_go_build:
    driver: local
