name: Test
on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
          cache-dependency-path: go.sum

      - name: go mod download
        run: go mod download

      - name: go generate 忘れを検出
        run: |
          go generate ./...
          git diff --exit-code -- ':(exclude)go.sum'

      - name: golangci-lint
        uses: golangci/golangci-lint-action@55c2c1448f86e01eaae002a5a3a9624417608d84 # v6
        with:
          version: v1.63.1

      - name: Install ffmpeg
        run: |
          sudo apt-get update
          sudo apt-get install ffmpeg -y

      - name: Run tests
        run: go test -cover ./... -coverprofile="cover.out"

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@0565863a31f2c772f9f0395002a31e3f06189574 # v5.4.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: cover.out
          fail_ci_if_error: false
          verbose: true

  status-check:
    runs-on: ubuntu-latest
    needs: [test]
    if: failure()
    steps:
      - run: exit 1
