name: Test
on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
          cache-dependency-path: go.sum

      - name: go mod download
        run: go mod download

      - name: go generate 忘れを検出
        run: |
          go generate ./...
          git diff --exit-code -- ':(exclude)go.sum'

      - name: golangci-lint
        uses: golangci/golangci-lint-action@9fae48acfc02a90574d7c304a1758ef9895495fa # v7.0.1
        with:
          install-mode: "goinstall"

      - name: Install ffmpeg
        run: |
          sudo apt-get update
          sudo apt-get install ffmpeg -y

      - name: Run tests
        run: go test -cover ./... -coverprofile="cover.out"

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@18283e04ce6e62d37312384ff67231eb8fd56d24 # v5.4.3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: cover.out
          fail_ci_if_error: false
          verbose: true

  status-check:
    runs-on: ubuntu-latest
    needs: [test]
    if: failure()
    steps:
      - run: exit 1
